version: '3'

services: 
  backend_thealfastore:
    container_name: backend_thealfastore
    image: backend
    restart: always
    build: 
      context: .
    ports:
      - "3000:3000"
    environment: 
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
volumes:
  nps_data: {}
