version: '3'

services: 
  backend_thealfastore:
    container_name: backend_thealfastore
    image: backend
    restart: always
    build: 
      context: .
    ports:
      - "3000:3000"
    environment: 
      - CLOUDINARY_CLOUD_NAME=dwmsky6nu
      - CLOUDINARY_API_KEY=982366275336271
      - CLOUDINARY_API_SECRET=3xYTMjv3JNbDdHjXPZVeoF9DdA4
      - DATABASE_MONGO_URI=mongodb+srv://Lucho:mision2017@db-alfastore.dknyvyl.mongodb.net/
volumes:
  nps_data: {}
